# Test backend changes with Accel-Sim

name: Short-Tests-AccelSim

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - "gh-readonly-queue**"
  merge_group:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# By default regress against accel-sim's dev branch
env:
  ACCELSIM_REPO: https://github.com/purdue-aalp/accel-sim-framework-public.git
  ACCELSIM_BRANCH: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-QV100:
    strategy:
      matrix:
        image_tags:
          - ubuntu-24.04-cuda-12.8-minimal
          - ubuntu-22.04-cuda-11.7.1-minimal
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/accel-sim/accel-sim-framework:${{ matrix.image_tags }}
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests-accelsim.sh

