# Workflow with cmake build system
name: Short-Tests-CMake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the mydev branch
  push:
    branches-ignore:
      - "gh-readonly-queue**"
  merge_group:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        app:
          - rodinia_2.0-ft
        config:
          - TITANV
          - TITANV-LOCALXBAR
          - QV100
          - RTX2060
          - RTX3070
        image_tags:
          - ubuntu-24.04-cuda-12.8-minimal
          - ubuntu-22.04-cuda-11.7.1-minimal
    runs-on: ubuntu-latest
    name: Build ${{ matrix.app }} on ${{ matrix.image_tags }} with ${{ matrix.config }}
    container:
      image: ghcr.io/accel-sim/accel-sim-framework:${{ matrix.image_tags }}
      env:
        CONFIG: ${{ matrix.config }}
        APP: ${{ matrix.app }}
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Simulation
        run: /bin/bash $GITHUB_WORKSPACE/short-tests-cmake.sh
